language: java
jdk:
- openjdk8
sudo: false

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify jacoco:report -B -V

after_success:
  - mvn coveralls:report

notifications:
  email:
    on_failure: always

cache:
  directories:
    - $HOME/.m2